table Dim_OrderReviewsDataset
	lineageTag: f7c1fb61-154f-4549-bc66-a93732e75803

	column review_id
		dataType: string
		lineageTag: e11f54a0-d94e-40b2-8358-27a193c093a2
		summarizeBy: none
		sourceColumn: review_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: aa8a2217-3b2b-4603-a64d-ecac8bb71790
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column review_score
		dataType: int64
		formatString: 0
		lineageTag: 0845d23f-8816-4723-a4c9-b254c55ba921
		summarizeBy: none
		sourceColumn: review_score

		annotation SummarizationSetBy = User

	column review_comment_title
		dataType: string
		lineageTag: f2d836d6-159b-4bc3-a1ba-27921c7fd29e
		summarizeBy: none
		sourceColumn: review_comment_title

		annotation SummarizationSetBy = Automatic

	column review_comment_message
		dataType: string
		lineageTag: 556fe7b6-11e7-4233-9be4-4409345e75a6
		summarizeBy: none
		sourceColumn: review_comment_message

		annotation SummarizationSetBy = Automatic

	column review_creation_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 625ecb2c-31c7-435d-b989-f3ab9d0ad29e
		summarizeBy: none
		sourceColumn: review_creation_date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column review_answer_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: f561145f-af7b-4874-ba21-ebff6ce3ca48
		summarizeBy: none
		sourceColumn: review_answer_timestamp

		annotation SummarizationSetBy = Automatic

	partition Dim_OrderReviewsDataset = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("G:\Meu Drive\Power BI Microsoft\ESTUDOS - PORTFOLIO\Super Market\SuperMarket\dataset\olist_order_reviews_dataset.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"review_id", type text}, {"order_id", type text}, {"review_score", Int64.Type}, {"review_comment_title", type text}, {"review_comment_message", type text}, {"review_creation_date", type datetime}, {"review_answer_timestamp", type datetime}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

