table FACT_SALES
	lineageTag: efd80567-b1fa-4731-a244-34f8589cbd69

	column invoiceid
		dataType: string
		lineageTag: acdc07ee-928a-408b-ad01-d8b436c480bc
		summarizeBy: none
		sourceColumn: invoiceid

		annotation SummarizationSetBy = Automatic

	column branch
		dataType: string
		lineageTag: 143a2085-3a34-43a2-8570-2aa0b6d28662
		summarizeBy: none
		sourceColumn: branch

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: ccda7d2b-f3f9-4459-8921-7e997b9ad8a9
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column customertype
		dataType: string
		lineageTag: 6a412a3d-125a-4e16-b755-cdaed184e7fd
		summarizeBy: none
		sourceColumn: customertype

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 581c005f-4f3c-42e8-a82f-8c5344768245
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column productline
		dataType: string
		lineageTag: f5fd3213-1a42-4261-8064-9dedefc52b3d
		summarizeBy: none
		sourceColumn: productline

		annotation SummarizationSetBy = Automatic

	column unitprice
		dataType: double
		lineageTag: c83fa061-3041-4322-84e4-9a4fd8d7d26e
		summarizeBy: sum
		sourceColumn: unitprice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: d674e644-bb4c-4323-96f2-c0bce642160e
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Short Date
		lineageTag: f5ed9455-aa08-4aa2-a859-db7493457b0b
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 3482bd13-d483-459a-a693-9a7a8fd6179d
		summarizeBy: none
		sourceColumn: time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column payment
		dataType: string
		lineageTag: 8f8d152b-8f24-4768-a8f3-de08a02eab03
		summarizeBy: none
		sourceColumn: payment

		annotation SummarizationSetBy = Automatic

	column rating
		dataType: double
		lineageTag: 815c5442-7ee8-4347-b8e4-e93ab57c8707
		summarizeBy: sum
		sourceColumn: rating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FACT_SALES = m
		mode: import
		source =
				let
				    Fonte = DataWorld.Dataset("eegonca", "supermarket", null),
				    supermarket_sales_sheet2 = Fonte{[tableId="supermarket_sales_sheet1"]}[Data],
				    #"Colunas Reordenadas" = Table.ReorderColumns(supermarket_sales_sheet2,{"invoiceid", "branch", "city", "customertype", "gender", "productline", "payment", "unitprice", "quantity", "tax5", "total", "date", "time", "cogs", "grossmarginpercentage", "grossincome", "rating"}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Reordenadas",{"total", "tax5", "cogs", "grossmarginpercentage", "grossincome"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

