table Medidas
	lineageTag: 49ff3a42-f468-4c48-a962-38692ded0aa2

	measure '01 Valor Total' = ```
			
			VAR Tax = 0.05
			
			RETURN
			
			SUMX(
			    FACT_SALES,
			    (FACT_SALES[unitprice] * FACT_SALES[quantity]) + 
			    (FACT_SALES[unitprice] * FACT_SALES[quantity]) * Tax
			)
			```
		lineageTag: 645d72f1-1061-4431-9666-b34fcfbd1c24

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '02 CMV' =
			
			SUMX(
			    FACT_SALES,
			    FACT_SALES[unitprice] * FACT_SALES[quantity]
			)
		lineageTag: 9852877b-6425-4245-aa93-e094ee6c7d82

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '03 Lucro Bruto Total' =
			
			VAR PercentMargin = 0.05
			
			RETURN
			
			SUMX(
			    FACT_SALES,
			    (FACT_SALES[unitprice] * FACT_SALES[quantity]) * PercentMargin
			)
		formatString: 0.00
		lineageTag: 006c7581-0376-4a7b-9dca-f77c9c920ffa

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	changedProperty = Name

	annotation PBI_ResultType = Table

